# Generated by Django 3.1 on 2020-09-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_payment_date', models.DateTimeField(blank=True, null=True)),
                ('value', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('R', 'Recebido'), ('A', 'A receber')], default='A', max_length=1)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeapp.incomeclassification')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeapp.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('value', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pago'), ('A', 'A pagar')], default='A', max_length=1)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeapp.expensesclassification')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeapp.paymentmethod')),
            ],
        ),
    ]
